name: dalgeurak
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.4+21

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  dio: ^4.0.1

  dimigoin_flutter_plugin: ^0.5.14
  dalgeurak_meal_application:
    git:
      url: https://github.com/dimigoin/dalgeurak-meal-application.git
      ref: main
  dalgeurak_widget_package:
    git:
      url: https://github.com/dimigoin/dalgeurak-widget-package.git
      ref: main

  firebase_core: ^1.24.0
  firebase_core_platform_interface: 4.5.1
  firebase_auth: ^3.1.4
  firebase_analytics: ^9.3.8
  firebase_performance: ^0.8.0+4
  firebase_remote_config: ^2.0.13
  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^9.7.0

  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0

  shared_preferences: ^2.0.15
  url_launcher: ^6.0.12
  permission_handler: ^8.2.5
  package_info_plus: ^1.2.0
  flutter_native_splash: ^2.0.4
  korea_regexp: ^0.1.0+1
  flutter_fgbg: ^0.1.0
  flutter_vibrate: ^1.3.0
  connectivity_plus: ^2.2.1
  upgrader: ^4.10.0
  version: ^3.0.2

  jiffy: ^4.1.0

  flutter_switch: ^0.3.2
  flutter_svg: ^0.23.0+1
  extended_image: ^6.2.1
  lottie: ^1.2.2
  flutter_custom_tab_bar: ^1.2.0
  table_calendar: ^3.0.7
  flutter_web_frame: ^0.0.3
  pull_to_refresh:
    git:
      url: https://github.com/miquelbeltran/flutter_pulltorefresh

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/lotties/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 200
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GmarketSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GmarketSans-Light.ttf
          weight: 300
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 900
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
    - family: MapleStory
      fonts:
        - asset: assets/fonts/MapleStory-Bold.ttf
          weight: 700
        - asset: assets/fonts/MapleStory-Light.ttf
          weight: 500
    - family: Pretendard
      fonts:
        - asset: packages/dalgeurak_widget_package/assets/fonts/Pretendard-Black.otf
          weight: 900
        - asset: packages/dalgeurak_widget_package/assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: packages/dalgeurak_widget_package/assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: packages/dalgeurak_widget_package/assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: packages/dalgeurak_widget_package/assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: packages/dalgeurak_widget_package/assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: packages/dalgeurak_widget_package/assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: packages/dalgeurak_widget_package/assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: packages/dalgeurak_widget_package/assets/fonts/Pretendard-Thin.otf
          weight: 100

flutter_native_splash:
  color: "#1564FF"
  image: assets/images/splashImage.png
  branding: assets/images/splashImageBranding.png

  android_gravity: center
  ios_content_mode: center
  branding_mode: bottom